# Generated by Django 4.2.4 on 2023-08-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DynamicTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tblname",
                    models.CharField(help_text="Dynamic table name", unique=True),
                ),
                ("columns", models.JSONField(help_text="Columns")),
            ],
        ),
    ]
