# Generated by Django 4.2.4 on 2023-08-05 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tblapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DynamicTable",
            new_name="DynamicTableModel",
        ),
    ]
