# Generated by Django 4.2.4 on 2023-08-05 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tblapp", "0002_rename_dynamictable_dynamictablemodel"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DynamicTableModel",
            new_name="DynTbl",
        ),
    ]
