# Generated by Django 4.2.4 on 2023-08-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tblapp", "0003_rename_dynamictablemodel_dyntbl"),
    ]

    operations = [
        migrations.AddField(
            model_name="dyntbl",
            name="testname",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
    ]
